name: Build and Push Docker Image to GHCR and Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/cornslop/comfyui-docker:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/comfyui-docker:latest
          # Use GitHub Actions cache for Docker layers to speed up builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
  prune-images:
    name: Prune old container images
    runs-on: ubuntu-latest
    needs: [build-and-push]
    
    steps:
      - name: Prune old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: ghcr.io/cornslop/comfyui-docker
          cut-off: 30 days ago UTC
          keep-at-least: 5
          account-type: personal
          token: ${{ secrets.GHCR_TOKEN }}
          skip-tags: latest
          timestamp-to-use: updated_at
          org-name: cornslop

